# https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

front-end:
  - changed-files:
      - any-glob-to-any-file: frontend/**

api:
  - changed-files:
      - any-glob-to-any-file: api/**

github:
  - changed-files:
      - any-glob-to-any-file: .github/**
