name: Run E2E tests
description: Run the E2E tests against an environment

inputs:
  database_url:
    description: The database URL to connect the API to
    required: true
  e2e_test_token:
    description: The token to use for authenticating the E2E test process
    required: false
    default: some-token
  disable_analytics_features:
    description: Disables analytics features.
    required: false
    default: 'false'

outputs:
  containerId:
    description: Docker container ID for the running Flagsmith API instance
    value: ${{ steps.run-api-container.outputs.containerId }}

runs:
  using: composite

  steps:
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
      with:
        oidc: true

    - name: Build temporary Docker image for running the API
      run: depot build --load -t flagsmith/flagsmith-api:e2e-${{ github.sha }} -f api/Dockerfile .
      shell: bash

    - name: Run the API
      id: run-api-container
      working-directory: api
      env:
        E2E_TEST_AUTH_TOKEN: ${{ inputs.e2e_test_token }}
        DATABASE_URL: ${{ inputs.database_url }}
        DISABLE_ANALYTICS_FEATURES: ${{ inputs.disable_analytics_features }}
      run: |
        CONTAINER_ID=$( docker run \
        -p 8000:8000 \
        -e DATABASE_URL=$DATABASE_URL \
        -e E2E_TEST_AUTH_TOKEN=$E2E_TEST_AUTH_TOKEN \
        -e DISABLE_ANALYTICS_FEATURES=$DISABLE_ANALYTICS_FEATURES \
        -e DJANGO_ALLOWED_HOSTS="*" \
        -e DJANGO_SETTINGS_MODULE=app.settings.test \
        -e ENABLE_FE_E2E=True \
        -e ACCESS_LOG_LOCATION=- \
        -d flagsmith/flagsmith-api:e2e-${{ github.sha }} )
        echo "containerId=$CONTAINER_ID" >> "$GITHUB_OUTPUT"
      shell: bash
