name: Run E2E tests in local environment
description: Run the E2E tests against local environment

inputs:
  slack_token:
    description: The slack authentication token.
    required: true
  tests:
    description: The space separated list of E2E tests to be executed.
    required: false
    default: ''
  concurrency:
    description: The concurrent number of browsers to be used on testing.
    required: false
    default: 3

runs:
  using: composite

  steps:
    - name: Run Local API
      id: run-local-api
      uses: ./.github/actions/run-local-api
      with:
        e2e_test_token: some-token
        # As per https://stackoverflow.com/q/65497331/421808 172.17.0.1 seems like the only way to resolve host DB
        database_url: postgres://postgres:postgres@172.17.0.1:5432/flagsmith
        disable_analytics_features: true

    - name: Run E2E tests against local
      uses: ./.github/actions/e2e-tests
      env:
        E2E_CONCURRENCY: ${{ inputs.concurrency }}
      with:
        e2e_test_token: some-token
        slack_token: ${{ inputs.slack_token }}
        environment: local
        tests: ${{ inputs.tests }}

    - name: Output API container status and logs
      if: failure()
      env:
        API_CONTAINER_ID: ${{ steps.run-local-api.outputs.containerId }}
      run: |
        docker inspect $API_CONTAINER_ID | jq '.[0].State'
        docker logs $API_CONTAINER_ID
      shell: bash
