name: API Publish Docker Images

on:
  push:
    tags:
      - '*'
    paths:
      - api/**
      - .github/**

jobs:
  build-api-dockerhub:
    runs-on: ubuntu-latest
    name: API Publish Docker Image

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            flagsmith/flagsmith-api
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Write git info to Docker image
        run: |
          echo ${{ github.sha }} > api/CI_COMMIT_SHA

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: docker_build
        uses: depot/build-push-action@v1
        with:
          platforms: linux/amd64,linux/arm64
          file: api/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
