name: Platform Publish Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest
    name: Platform Publish Docker Image

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Checkout Target Charts Repository to update yaml
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-charts
          path: chart
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            flagsmith/flagsmith
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Write git info to Docker image
        run: |
          echo ${{ github.sha }} > api/CI_COMMIT_SHA

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: docker_build
        uses: depot/build-push-action@v1
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .

      - name: Set up release tag variables
        run: |
          TAG=${{github.ref_name}}
          echo "version_trim=${TAG#v}" >> $GITHUB_ENV

      - name: Run YAML to Github Output Action
        id: yaml-output
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: './chart/charts/flagsmith/Chart.yaml'

      - uses: us-ignite/action-bump-semver@main
        id: bump-semver
        with:
          current_version: ${{ steps.yaml-output.outputs.version }}
          level: minor

      - name: Update flagsmith-charts values.yaml with latest docker version
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.FLAGSMITH_CHARTS_GITHUB_TOKEN }}
          repository: flagsmith/flagsmith-charts
          workDir: chart
          masterBranchName: 'main'
          targetBranch: 'main'
          branch: docker-image-version-bump-${{ env.version_trim }}
          commitChange: true
          createPR: true
          message: 'Flagsmith docker image version bump'
          description: 'Automated PR generated by a release event in https://github.com/Flagsmith/flagsmith'
          valueFile: 'charts/flagsmith/Chart.yaml'
          changes: |
            {
              "appVersion": "${{ env.version_trim }}",
              "version": "${{ steps.bump-semver.outputs.new_version }}"
            }
