name: Publish Flagsmith Private Cloud Image

on:
  push:
    tags:
      - '*'

env:
  FLAGSMITH_SAML_REVISION: v1.4.0
  FLAGSMITH_RBAC_REVISION: v0.7.0
  FLAGSMITH_AUTH_CONTROLLER_REVISION: v0.0.1

jobs:
  build-dockerhub:
    name: Platform Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Checkout SAML package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-saml
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_saml_revision }}
          path: ./flagsmith-saml

      - name: Integrate SAML module
        run: |
          mv ./flagsmith-saml/saml ./api

      - name: Checkout Auth Controller package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-auth-controller
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.FLAGSMITH_AUTH_CONTROLLER_REVISION }}
          path: ./flagsmith-auth-controller

      - name: Integrate Auth Controller module
        run: mv ./flagsmith-auth-controller/auth_controller ./api
        shell: bash

      - name: Checkout RBAC module
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-rbac
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_rbac_revision }}
          path: ./flagsmith-rbac

      - name: Integrate RBAC module
        run: mv ./flagsmith-rbac/rbac ./api
        shell: bash

      - name: Write git info to Docker image
        run: |
          cd api
          echo ${{ github.sha }} > CI_COMMIT_SHA
          echo '' > ENTERPRISE_VERSION

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            flagsmith/flagsmith-private-cloud
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: docker_build
        uses: depot/build-push-action@v1
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          build-args: |
            SAML_INSTALLED=1
            POETRY_OPTS=--with saml,auth-controller,ldap,workflows
            GH_TOKEN=${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
